// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvYpS7WUO0ZV-5ApEu4uhpLUot2G5WkDA',
    appId: '1:801307611460:web:a4b2154354861a5ac9c711',
    messagingSenderId: '801307611460',
    projectId: 'takipversi1',
    authDomain: 'takipversi1.firebaseapp.com',
    storageBucket: 'takipversi1.firebasestorage.app',
    measurementId: 'G-1RKWW822K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWIFaooJ-yL3_U1gtRPdHzTy0cw9jMLgg',
    appId: '1:801307611460:android:f4640801a3c88d04c9c711',
    messagingSenderId: '801307611460',
    projectId: 'takipversi1',
    storageBucket: 'takipversi1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQB1D3hIf0o3_y5csU2pREPwuKkxwRYGk',
    appId: '1:801307611460:ios:a4ff00f8a31a42d5c9c711',
    messagingSenderId: '801307611460',
    projectId: 'takipversi1',
    storageBucket: 'takipversi1.firebasestorage.app',
    iosClientId: '801307611460-ttooj37oeoe4dbptf1qkqoddesjfqpnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.takipversie1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQB1D3hIf0o3_y5csU2pREPwuKkxwRYGk',
    appId: '1:801307611460:ios:a4ff00f8a31a42d5c9c711',
    messagingSenderId: '801307611460',
    projectId: 'takipversi1',
    storageBucket: 'takipversi1.firebasestorage.app',
    iosClientId: '801307611460-ttooj37oeoe4dbptf1qkqoddesjfqpnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.takipversie1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvYpS7WUO0ZV-5ApEu4uhpLUot2G5WkDA',
    appId: '1:801307611460:web:53e0a1541f84ff0ac9c711',
    messagingSenderId: '801307611460',
    projectId: 'takipversi1',
    authDomain: 'takipversi1.firebaseapp.com',
    storageBucket: 'takipversi1.firebasestorage.app',
    measurementId: 'G-TFL3FD8DZ8',
  );
}
