name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.x' # Or specific version if preferred

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: |
          # --base-href /repo_name/ formatting is critical for GitHub Pages
          flutter build web --release --base-href "/takipversie1/" --web-renderer canvaskit

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
